#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xbfEBCB8B     \
    active_window_border_color   0xFF2e3440     \
    normal_window_border_color   0x00FFFFFF     \
    window_border_width          1              \
    window_border_radius         12             \
    window_border_blur           on             \
    window_border_hidpi          on             \
    window_border                on             \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  0              \
    bottom_padding               0              \
    left_padding                 0              \
    right_padding                0              \
    window_gap                   0              \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# yabai -mspace 3 --padding abs:<top>:<bottom>:<left>:<right>

yabai -m space 1 --label main
yabai -m space 1 --padding abs:40:40:50:50
yabai -m space 1 --gap abs:7

yabai -m space 2 --label term
yabai -m space 2 --padding abs:24:24:30:30
yabai -m space 2 --gap abs:1

yabai -m space 3 --label code
yabai -m space 3 --padding abs:24:24:30:30
yabai -m space 3 --gap abs:0

yabai -m space 4 --label browse
yabai -m space 4 --padding abs:40:40:30:30
yabai -m space 4 --gap abs:7

yabai -m space 5 --label social
yabai -m space 5 --padding abs:40:40:30:30
yabai -m space 5 --gap abs:7

# gridh:gridw:lpad:tpad:width:height

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" opacity=0.75
yabai -m rule --add label="Finder2" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off border=off
yabai -m rule --add app="Alacritty" space=^2
yabai -m rule --add app="Code" space^3 opacity=0.75
yabai -m rule --add app="Firefox*" space=^4
yabai -m rule --add app="Google Chrome" space=^4
yabai -m rule --add app="FaceTime" space=^5 manage=off grid="20:20:1:0:19:20" border=off
yabai -m rule --add app="Messages" space=^5 manage=off grid="20:10:0:0:3:20" opacity=0.7

echo "yabai configuration loaded.."